= Sean Yap - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: PlanMySem

---

== Overview

This portfolio documents my contributions to *PlanMySem*, a CLI (Command Line Interface) scheduling/calendar application
that targets NUS students and staff who prefer to use a desktop application for managing their schedule/calendar.
The application was morphed from https://github.com/CS2113-AY1819S2-T08-3/main[AddressBook Level 3] for CS2113T, a
software engineering module in the National University of Singapore (NUS).

It was a combined effort between a team of 4, <<marcus-pzj#, Marcus>>, <<macchazuki#, Jullian>>, <<dingheng4448#, Ding Heng>>
and myself, in which I served as the team lead.

I was responsible for the slot management feature (add, edit and delete commands) and the structure of the codebase.

The following sections will illustrate these enhancements in more detail as well as the respective changes that i have made to both the user guide and developer guide.

== Summary of contributions
This section shows a summary of my coding, documentation, and other helpful contributions to the team project.

My coding contributions can be summarised in these parts:
* The slot management feature consist of three parts, add, edit and delete.
* Additionally,

Enhancement added: I added the ability to undo and redo previous commands
• What it does: The undo command allows the user to undo a previous command.
The user may reverse this undo command with the redo command.
• Justification: In the event that users have made a mistake or changed their minds about executing a command, the undo command enables them to revert to a version immediately before the mistaken command was executed. If they change their minds again and decide to execute the command after all, then the redo command enables them to do so easily.
• Highlights: This enhancement works with existing as well as future commands. An in-depth analysis of design alternatives was necessary to... The implementation was also challenging as it required changes to existing commands.
• Credits: {mention here if you reused any code/ideas from elsewhere or if a third-party library is heavily used in the feature so that

== Contributions to the User Guide
This section shows my contributions I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._

include::../UserGuide.adoc[tag=importICS]

include::../UserGuide.adoc[tag=dataencryption]

== Contributions to the Developer Guide
This section shows my contributions to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._

include::../DeveloperGuide.adoc[Slot-Management]

include::../DeveloperGuide.adoc[tag=Slot-Management]


== PROJECT: PowerPointLabs

---

_{Optionally, you may include other projects in your portfolio.}_
